#!/bin/bash

# Source our current dotfiles environment.
source ~/.dotfiles_env 2>/dev/null

case "$DOTFILES_ENV" in
  vizworx)
    xrandr --output VGA-1 --auto --primary
    ;;
  vm)
    xrandr --output VGA-0 --auto --primary --output VGA-1 --auto --right-of VGA-0
    ;;
esac
