#!/bin/bash

# Source our current dotfiles environment.
source ~/.dotfiles_env 2>/dev/null

case "$DOTFILES_ENV" in
  simplesimple)
    xrandr --output DFP6 --auto --primary --output CRT1 --auto --right-of DFP6
    ;;
  aware360)
    xrandr --output VBOX0 --auto --primary --output VBOX1 --auto --right-of VBOX0
    ;;
  vizworx)
    xrandr --output VGA-1 --auto --primary
    ;;
  vm)
    xrandr --output VGA-0 --auto --primary --output VGA-1 --auto --right-of VGA-0
    ;;
esac
