#!/bin/bash

player_status=$(playerctl status 2> /dev/null)
if [[ $? -ne 0 || $player_status != "Playing" ]]; then
  echo ""
  exit 0
fi

echo "$(playerctl metadata artist 2> /dev/null) - $(playerctl metadata title 2> /dev/null)"
